services:
    app:
        build:
            args:
                user: ${USER}
                uid: ${UID}
            context: .
            dockerfile: docker/Dockerfile
        image: app
        depends_on:
            - db
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/html
            - .env:/var/www/html/.env
        networks:
            - locadora-network
        environment:
            - "USER=${USER}"
            - "UID=${UID}"

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - 8090:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - locadora-network

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - locadora-network

networks:
    locadora-network:
        driver: bridge
